included:
 - Sources

disabled_rules:
 - trailing_whitespace
 - cyclomatic_complexity

excluded:
  - Carthage
  - Pods

force_try: warning
force_cast: warning

line_length: 200
type_body_length:
 - 300 # warning
 - 400 # error

colon:
  apply_to_dictionaries: true
variable_name:
  excluded:
    - id
statement_position:
   statement_mode: uncuddled_else

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle)
